# Generated by Django 2.2.6 on 2019-11-25 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busNumber', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('complaint_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 25, 6, 45, 50, 247432))),
            ],
        ),
    ]
