# Generated by Django 2.2.6 on 2019-11-25 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 25, 6, 55, 4, 712450)),
        ),
    ]
