# Generated by Django 2.2.7 on 2019-11-25 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_auto_20191125_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 25, 18, 34, 10, 614745)),
        ),
    ]
