# Generated by Django 2.2.6 on 2019-11-25 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_auto_20191125_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 25, 15, 48, 7, 320061)),
        ),
    ]
