# Generated by Django 2.2.6 on 2019-11-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        ('students', '0008_auto_20191124_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.BooleanField(default=False)),
                ('dateOfIssue', models.DateField(null=True)),
                ('dateOfExpiry', models.DateField(null=True)),
                ('isCardValid', models.BooleanField(default=True, null=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='institution.Institution')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='students.Student')),
            ],
        ),
    ]
