# Generated by Django 2.2.6 on 2019-11-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='institution.Institution'),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.Student'),
        ),
    ]
