# Generated by Django 2.2.7 on 2019-11-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='isCardValid',
            field=models.BooleanField(default=True),
        ),
    ]
