# Generated by Django 2.2.6 on 2019-11-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDetails', '0002_auto_20191124_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='institution',
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='students.Student'),
        ),
    ]
