# Generated by Django 2.2.6 on 2019-11-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardDetails', '0004_auto_20191124_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
