# Generated by Django 2.2.7 on 2019-11-25 18:30

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        ('cardDetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, null=True)),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('dob', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to=students.models.uploadImage)),
                ('start1', models.CharField(blank=True, max_length=250, null=True)),
                ('stop1', models.CharField(blank=True, max_length=250, null=True)),
                ('start2', models.CharField(blank=True, max_length=250, null=True)),
                ('stop2', models.CharField(blank=True, max_length=250, null=True)),
                ('start3', models.CharField(blank=True, max_length=250, null=True)),
                ('stop3', models.CharField(blank=True, max_length=250, null=True)),
                ('start4', models.CharField(blank=True, max_length=250, null=True)),
                ('stop4', models.CharField(blank=True, max_length=250, null=True)),
                ('card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cardDetails.CardInfo')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
        ),
    ]
