# Generated by Django 2.2.6 on 2019-11-25 06:45

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('image', models.ImageField(null=True, upload_to=students.models.uploadImage)),
                ('start1', models.CharField(blank=True, max_length=250)),
                ('stop1', models.CharField(blank=True, max_length=250)),
                ('start2', models.CharField(blank=True, max_length=250)),
                ('stop2', models.CharField(blank=True, max_length=250)),
                ('start3', models.CharField(blank=True, max_length=250)),
                ('stop3', models.CharField(blank=True, max_length=250)),
                ('start4', models.CharField(blank=True, max_length=250)),
                ('stop4', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
