# Generated by Django 2.2.7 on 2019-11-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191126_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
