# Generated by Django 2.2.13 on 2020-10-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20191126_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
