# Generated by Django 2.2.6 on 2019-11-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20191109_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.Student')),
                ('dateOfIssue', models.DateField()),
                ('dateOfExpiry', models.DateField()),
                ('isCardValid', models.BooleanField()),
                ('isApproved', models.BooleanField()),
                ('start1', models.CharField(blank=True, max_length=250)),
                ('stop1', models.CharField(blank=True, max_length=250)),
                ('start2', models.CharField(blank=True, max_length=250)),
                ('stop2', models.CharField(blank=True, max_length=250)),
                ('start3', models.CharField(blank=True, max_length=250)),
                ('stop3', models.CharField(blank=True, max_length=250)),
                ('start4', models.CharField(blank=True, max_length=250)),
                ('stop4', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='courseOfStudy',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dateOfExpiry',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dateOfIssue',
        ),
        migrations.RemoveField(
            model_name='student',
            name='durationOfCourse',
        ),
        migrations.RemoveField(
            model_name='student',
            name='endingpoint1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='endingpoint2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='endingpoint3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='endingpoint4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='isApproved',
        ),
        migrations.RemoveField(
            model_name='student',
            name='isCardValid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nameOfInstitution',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='startingpoint1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='startingpoint2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='startingpoint3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='startingpoint4',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.Student')),
                ('course', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.ChoiceList')),
            ],
        ),
    ]
