# Generated by Django 2.2.6 on 2019-11-24 14:05

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20191124_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='id',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='start1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='start2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='start3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='start4',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='stop1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='stop2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='stop3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='stop4',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to=students.models.uploadImage),
        ),
        migrations.DeleteModel(
            name='CardDetails',
        ),
        migrations.DeleteModel(
            name='ChoiceList',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
