version: "3.8"
   
services:
  db:
    image: keinos/sqlite3:latest
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/StudentTicket
    ports:
      - "8000:8000"
    depends_on:
      - db