# Generated by Django 2.2.6 on 2019-11-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(default='Model Engineering College', max_length=200),
        ),
        migrations.DeleteModel(
            name='ChoiceList',
        ),
    ]
